// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnionArc.Persistence.Context;

#nullable disable

namespace OnionArc.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250404162508_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CategoryProduct", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("int");

                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.HasKey("CategoriesId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("CategoryProduct");
                });

            modelBuilder.Entity("OnionArc.Domain.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 4, 4, 16, 25, 8, 55, DateTimeKind.Utc).AddTicks(2666),
                            IsDeleted = false,
                            Logo = "https://picsum.photos/640/480/?image=81",
                            Name = "Sports, Books & Outdoors",
                            UpdatedDate = new DateTime(2025, 4, 4, 16, 25, 8, 55, DateTimeKind.Utc).AddTicks(2876)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 4, 4, 16, 25, 8, 55, DateTimeKind.Utc).AddTicks(3364),
                            IsDeleted = true,
                            Logo = "https://picsum.photos/640/480/?image=739",
                            Name = "Shoes, Computers & Automotive",
                            UpdatedDate = new DateTime(2025, 4, 4, 16, 25, 8, 55, DateTimeKind.Utc).AddTicks(3364)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 4, 4, 16, 25, 8, 55, DateTimeKind.Utc).AddTicks(3422),
                            IsDeleted = false,
                            Logo = "https://picsum.photos/640/480/?image=158",
                            Name = "Sports",
                            UpdatedDate = new DateTime(2025, 4, 4, 16, 25, 8, 55, DateTimeKind.Utc).AddTicks(3422)
                        });
                });

            modelBuilder.Entity("OnionArc.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("Priorty")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 4, 4, 16, 25, 8, 56, DateTimeKind.Utc).AddTicks(2216),
                            IsDeleted = false,
                            Name = "Electronics",
                            ParentId = 0,
                            Priorty = 1,
                            UpdatedDate = new DateTime(2025, 4, 4, 16, 25, 8, 56, DateTimeKind.Utc).AddTicks(2216)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 4, 4, 16, 25, 8, 56, DateTimeKind.Utc).AddTicks(2219),
                            IsDeleted = false,
                            Name = "Moda",
                            ParentId = 0,
                            Priorty = 2,
                            UpdatedDate = new DateTime(2025, 4, 4, 16, 25, 8, 56, DateTimeKind.Utc).AddTicks(2219)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 4, 4, 16, 25, 8, 56, DateTimeKind.Utc).AddTicks(2221),
                            IsDeleted = false,
                            Name = "Computer",
                            ParentId = 1,
                            Priorty = 1,
                            UpdatedDate = new DateTime(2025, 4, 4, 16, 25, 8, 56, DateTimeKind.Utc).AddTicks(2221)
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 4, 4, 16, 25, 8, 56, DateTimeKind.Utc).AddTicks(2223),
                            IsDeleted = false,
                            Name = "Woman",
                            ParentId = 2,
                            Priorty = 1,
                            UpdatedDate = new DateTime(2025, 4, 4, 16, 25, 8, 56, DateTimeKind.Utc).AddTicks(2223)
                        });
                });

            modelBuilder.Entity("OnionArc.Domain.Entities.Detail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Details");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 4, 4, 16, 25, 8, 68, DateTimeKind.Utc).AddTicks(2219),
                            Description = "Aut oldular kalemi ki. Alias incidunt numquam ea ducimus quis sandalye voluptatem teldeki. Non commodi mi voluptatem.",
                            IsDeleted = false,
                            Title = "Gorgeous Fresh Bacon",
                            UpdatedDate = new DateTime(2025, 4, 4, 16, 25, 8, 68, DateTimeKind.Utc).AddTicks(2225)
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 4, 4, 16, 25, 8, 68, DateTimeKind.Utc).AddTicks(2612),
                            Description = "Kapının voluptatem consequatur kapının nostrum ducimus beğendim. Türemiş kulu ea sinema olduğu odit un quia ama.",
                            IsDeleted = false,
                            Title = "Handcrafted Concrete Cheese",
                            UpdatedDate = new DateTime(2025, 4, 4, 16, 25, 8, 68, DateTimeKind.Utc).AddTicks(2612)
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 4, 4, 16, 25, 8, 68, DateTimeKind.Utc).AddTicks(2697),
                            Description = "Quia sevindi göze quam. Değerli mutlu velit yapacakmış yaptı nemo eius çünkü.",
                            IsDeleted = true,
                            Title = "Gorgeous Metal Table",
                            UpdatedDate = new DateTime(2025, 4, 4, 16, 25, 8, 68, DateTimeKind.Utc).AddTicks(2698)
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2025, 4, 4, 16, 25, 8, 68, DateTimeKind.Utc).AddTicks(2803),
                            Description = "Aliquid eius sequi sarmal reprehenderit voluptate consequatur. De layıkıyla explicabo exercitationem doloremque tempora doğru gazete quia gülüyorum. Sandalye sarmal ipsa gazete aliquid esse illo blanditiis exercitationem.",
                            IsDeleted = false,
                            Title = "Rustic Plastic Table",
                            UpdatedDate = new DateTime(2025, 4, 4, 16, 25, 8, 68, DateTimeKind.Utc).AddTicks(2804)
                        });
                });

            modelBuilder.Entity("OnionArc.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            CreatedDate = new DateTime(2025, 4, 4, 16, 25, 8, 72, DateTimeKind.Utc).AddTicks(641),
                            Description = "Sed doloremque karşıdakine gitti et quia lambadaki quia aut bahar. Sarmal sevindi quia veniam voluptas sokaklarda. Adanaya illo vel camisi gülüyorum. Bilgiyasayarı sayfası oldular quam çünkü modi. Veniam illo çünkü için quia.",
                            Discount = 15.001690656717500m,
                            IsDeleted = false,
                            Price = 570.573794045369800m,
                            Title = "Sleek Soft Car",
                            UpdatedDate = new DateTime(2025, 4, 4, 16, 25, 8, 72, DateTimeKind.Utc).AddTicks(644)
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 2,
                            CreatedDate = new DateTime(2025, 4, 4, 16, 25, 8, 72, DateTimeKind.Utc).AddTicks(1017),
                            Description = "Alias salladı kulu adresini et. Enim aut gitti magnam çorba velit. Kapının quis cezbelendi olduğu batarya yaptı. Odio bahar rem minima veniam oldular koştum praesentium ut. Labore bilgisayarı de ut corporis quia umut uzattı.",
                            Discount = 49.607322217246200m,
                            IsDeleted = false,
                            Price = 230.539759173509500m,
                            Title = "Fantastic Frozen Cheese",
                            UpdatedDate = new DateTime(2025, 4, 4, 16, 25, 8, 72, DateTimeKind.Utc).AddTicks(1018)
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 3,
                            CreatedDate = new DateTime(2025, 4, 4, 16, 25, 8, 72, DateTimeKind.Utc).AddTicks(1068),
                            Description = "Autem blanditiis ekşili totam. Et çarpan aperiam.",
                            Discount = 83.669411158911900m,
                            IsDeleted = false,
                            Price = 574.973106397681600m,
                            Title = "Unbranded Wooden Tuna",
                            UpdatedDate = new DateTime(2025, 4, 4, 16, 25, 8, 72, DateTimeKind.Utc).AddTicks(1068)
                        });
                });

            modelBuilder.Entity("CategoryProduct", b =>
                {
                    b.HasOne("OnionArc.Domain.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnionArc.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnionArc.Domain.Entities.Detail", b =>
                {
                    b.HasOne("OnionArc.Domain.Entities.Category", "Category")
                        .WithMany("Details")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("OnionArc.Domain.Entities.Product", b =>
                {
                    b.HasOne("OnionArc.Domain.Entities.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("OnionArc.Domain.Entities.Category", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
